<?php
// Add CSS files
function bleachwave_add_styles() {
	wp_enqueue_style( 'fonts', 'http://fonts.googleapis.com/css?family=Lato:400,700|Lora:400,400italic,700,700italic|Special+Elite', false,null );
	wp_enqueue_style( 'style', get_template_directory_uri() . '/style.min.css', array('fonts'), null);
	wp_enqueue_style( 'lightbox-style', get_template_directory_uri() . '/inc/lightbox/css/jquery.fancybox.css', array('style'),null );
}
add_action( 'wp_enqueue_scripts', 'bleachwave_add_styles' );

// Add JavaScript files
function bleachwave_add_scripts() {
	wp_deregister_script( 'jquery' );
	wp_register_script( 'jquery', get_template_directory_uri() . '/js/jquery-1.11.1.min.js', false, '1.11.1', true );
	wp_enqueue_script( 'jquery' );
    wp_enqueue_script( 'fancybox', get_template_directory_uri() . '/inc/lightbox/js/jquery.fancybox.pack.js', array( 'jquery' ), null, true );
    wp_enqueue_script( 'lightbox', get_template_directory_uri() . '/inc/lightbox/js/lightbox.js', array( 'fancybox' ), null, true );
    // wp_enqueue_script( 'app', get_template_directory_uri() . '/js/app.js', array( 'jquery' ), null, true );
}
add_action( 'wp_enqueue_scripts', 'bleachwave_add_scripts' );

// Enable post thumbnails
add_theme_support('post-thumbnails');
set_post_thumbnail_size(100, 100, true);

remove_action( 'wp_head', 'feed_links_extra', 3 ); // Display the links to the extra feeds such as category feeds
remove_action( 'wp_head', 'feed_links', 2 ); // Display the links to the general feeds: Post and Comment Feed
remove_action( 'wp_head', 'rsd_link' ); // Display the link to the Really Simple Discovery service endpoint, EditURI link
remove_action( 'wp_head', 'wlwmanifest_link' ); // Display the link to the Windows Live Writer manifest file.
remove_action( 'wp_head', 'index_rel_link' ); // index link
remove_action( 'wp_head', 'parent_post_rel_link', 10, 0 ); // prev link
remove_action( 'wp_head', 'start_post_rel_link', 10, 0 ); // start link
remove_action( 'wp_head', 'adjacent_posts_rel_link', 10, 0 ); // Display relational links for the posts adjacent to the current post.
remove_action( 'wp_head', 'adjacent_posts_rel_link_wp_head', 10, 0 ); // Display relational links for the posts adjacent to the current post.
remove_action( 'wp_head', 'wp_generator' ); // Display the XHTML generator that is generated on the wp_head hook, WP version

// ART GALLERY Custom Post Type Functions
require_once( 'functions-art.php' );

// Read more link does not jump down page on pageload 
function remove_more_jump_link($link) { 
	$offset = strpos($link, '#more-');
	if ($offset) {
		$end = strpos($link, '"',$offset);
	}
	if ($end) {
		$link = substr_replace($link, '', $offset, $end-$offset);
	}
	return $link;
}
add_filter( 'the_content_more_link', 'remove_more_jump_link' );

// Convert p tags around images to div tags
function filter_ptags_on_images($content) {
  return preg_replace('/<p[^>]*>\\s*?(<a .*?><img.*?><\\/a>|<img.*?>)?\\s*<\/p>/', '<div class="post-image">$1</div>', $content);
}
add_filter('the_content', 'filter_ptags_on_images');

// Remove CSS output generated by WordPress for Galleries
function bleachwave_remove_gallery_css( $css ) {
	return preg_replace( "#<style type='text/css'>(.*?)</style>#s", '', $css );
}
add_filter( 'gallery_style', 'bleachwave_remove_gallery_css' );

// Remove title attribute from category links
function wp_list_categories_remove_title_attributes($output) {
    $output = preg_replace('` title="(.+)"`', '', $output);
    return $output;
}
add_filter('wp_list_categories', 'wp_list_categories_remove_title_attributes');

/**
 * Remove inline styles from div.wp-caption
 * Solution found at: wordpress.org/support/topic/stripping-inline-width-style-for-wp_caption-on-images
 */
add_shortcode('wp_caption', 'fixed_img_caption_shortcode');
add_shortcode('caption', 'fixed_img_caption_shortcode');
function fixed_img_caption_shortcode($attr, $content = null) {
	if ( ! isset( $attr['caption'] ) ) {
		if ( preg_match( '#((?:<a [^>]+>\s*)?<img [^>]+>(?:\s*</a>)?)(.*)#is', $content, $matches ) ) {
			$content = $matches[1];
			$attr['caption'] = trim( $matches[2] );
		}
	}
	$output = apply_filters('img_caption_shortcode', '', $attr, $content);
	if ( $output != '' )
		return $output;
	extract(shortcode_atts(array(
		'id'	=> '',
		'align'	=> 'alignnone',
		'width'	=> '',
		'caption' => ''
	), $attr));
	if ( 1 > (int) $width || empty($caption) )
		return $content;
	if ( $id ) $id = 'id="' . esc_attr($id) . '" ';
	return '<div ' . $id . 'class="wp-caption ' . esc_attr($align) . '" >' 
			. do_shortcode( $content ) . '<p class="wp-caption-text">' . $caption . '</p></div>';
}

/* Add caption as title attribute to gallery images */
function add_title_attachment_link($link, $id = null) {
	$id = intval( $id );
	$_post = get_post( $id );
	$post_title = esc_attr( $_post->post_excerpt );
	return str_replace('<a href', '<a title="'. $post_title .'" href', $link);
}
add_filter('wp_get_attachment_link', 'add_title_attachment_link', 10, 2);

function insert_fb_in_head() {
	global $post;
	if (is_singular('art') || is_singular('post')) {
		if(has_post_thumbnail($post->ID)) {
			$thumb_url = wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), 'medium');
			echo '<meta property="og:image" content="' . esc_attr($thumb_url[0]) . '">
';
		}
	}
}
add_action('wp_head','insert_fb_in_head',1);

?>